spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/reservationService
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update



